TrajectoryPlannerROS:
  
  max_vel_x: 2.0
  min_vel_x: 0.05
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 5.0
  acc_lim_x: 5.0
  acc_lim_y: 5.0

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  sim_time: 1.0

  meter_scoring: true
  pdist_scale: 1.5
  gdist_scale: 0.2
  controller_frequency: 15.0
  holonomic_robot: false
